### ISSUE TITLE
How to build this project

### ISSUE THREAD

**Issue by Morph21** [TimoStaudinger/sprite#100]
Hi,

I would like to build that project and try a few things, could you please tell me how to do that?

**Comment by TimoStaudinger** [comment]
Hey, this project is built around Vercel's (formerly Zeit) serverless platform, and it should be runnable using their CLI.

It's been a little while, but I'll try to find some time to document how to run it locally in the readme over the next few days.

**Comment by Morph21** [comment]
Thanks, that will be a huge help :)
