### ISSUE TITLE
We need a logo!

### ISSUE THREAD

**Issue by TimoStaudinger** [TimoStaudinger/sprite#5]
TIme to be creative -- we need a logo for the favicon, header etc.

**Comment by mirzazulfan** [comment]
Hi @TimoSta , I've designed a logo for your project. What do you think? if you need to change please let me know and if you have an idea please share with me, it would be better for me. Best Regard.
![SPRITE](https://user-images.githubusercontent.com/36124339/54339439-69ac8300-4667-11e9-8ebb-b219c4459dfe.png)
